### ISSUE TITLE
repeating error

### ISSUE THREAD

**Issue by InsanePhin** [monun/auto-reloader#1]
```shell
[23:36:10] [Server thread/WARN]: [AutoReloader] Task #9 for AutoReloader v0.0.2 generated an exception
java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
        at com.github.monun.autoreloader.plugin.AutoReloaderPlugin.watch$lambda-4(AutoReloaderPlugin.kt:56) ~[?:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1672) ~[?:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?]
        at com.github.monun.autoreloader.plugin.AutoReloaderPlugin.watch(AutoReloaderPlugin.kt:53) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.17.1.jar:3208-Spigot-18c71bf-97f629b]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

plugins/update 폴더에 업로드 후 자동으로 업데이트를 하는데 초마다 이 에러가 꾸준하게 뜨네요.

config.yml에서 countdown-ticks: 20 으로 바꾼것 말고는 변경사항이 없습니다.

![image](https://user-images.githubusercontent.com/61483137/129216435-f02fca97-8fac-40b1-839d-1228201e7a98.png)

**Comment by monun** [comment]
paper사용중이신가요?

**Comment by InsanePhin** [comment]
spigot 사용중입니다
![image](https://user-images.githubusercontent.com/61483137/129219050-c0c30aa2-99ea-44f3-a6ae-6e1a0ae7d3d4.png)

**Comment by monun** [comment]
paper 전용이옵니다 ㅜㅜ

**Comment by InsanePhin** [comment]
앗 제가 확인하지 못해 발생한 문제군요
바쁘실텐데 죄송합니다ㅠㅠ

**Comment by InsanePhin** [comment]
+ 왜인지 모르겠지만 일부 플러그인엔 또 작동하네요...
