### ISSUE TITLE
페이퍼 새 업데이트 때문에........ 고장나버린

### ISSUE THREAD

**Issue by highright1234** [monun/auto-reloader#3]
최근 새로운 플러그인쪽 업데이트 떄문에
플러그인 로더를 바꾸면서 생긴걸로 추정되네유

```
[18:29:21 WARN]: java.lang.NullPointerException: Cannot invoke "java.io.File.mkdirs()" because "updateDirectory" is null
[18:29:21 WARN]:        at auto-reloader-0.0.5.jar//io.github.monun.autoreloader.plugin.AutoReloaderPlugin.onEnable(AutoReloaderPlugin.java:31)
[18:29:21 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[18:29:21 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192)
[18:29:21 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[18:29:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[18:29:21 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:561)
[18:29:21 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:472)
[18:29:21 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[18:29:21 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[18:29:21 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[18:29:21 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[18:29:21 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[18:29:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by monun** [comment]
하위호환 왜 안해주는..

**Comment by highright1234** [comment]
ㄹㅇㅋㅋ
